### ISSUE TITLE
PySCF DFT method and related options (functional, etc.)

### ISSUE THREAD

**Issue by bbusemeyer** [lkwagner/autogenv2#10]
Allow PySCF to use DFT methods to generate trial wavefunction.

**Comment by bbusemeyer** [comment]
methods are RKS and UKS, they're in a different module within pyscf. Should we only load the modules from pyscf that we need?

**Comment by lkwagner** [comment]
It should be ok to just load everything if that makes it easier to write the input file. It shouldn't incur too much of a cost.

**Comment by lkwagner** [comment]
Done.
