### ISSUE TITLE
PySCFReader should read data from chkfile instead of output.

### ISSUE THREAD

**Issue by bbusemeyer** [lkwagner/autogenv2#16]
Currently PySCFReader reads in results by scanning the text of the pyscf output. Instead we should grab the data from the chkfile produced by the calculation, which stores the results in hdf5 format. 

pyscf.lib.chkfile.load('chkfile_name','key')

will do it. 'key' is usually 'scf', but I'm not sure if this will change for different calculations.

**Comment by sunqm** [comment]
By now, only mcscf and scf results and intermediates are stored in chkfile.  Keys in chkfile are basically the same to the attributes of scf and mcscf object.  It supports a fast load through python language sugar
mc = mcscf.CASSCF(mf, norb, ne)
mc.\_\_dict\_\_.update(lib.chkfile.load('chkfile_name', 'mcscf')

This mechanism will not be changed in future updates.  More keys may be added to the chkfile depending on the progress of the code.

**Comment by bbusemeyer** [comment]
Awesome! This sounds very useful for reproducibility.

**Comment by bbusemeyer** [comment]
Just added this.
